#!/bin/bash
###############################################################################
#
# Forked from https://github.com/inkarkat/todo.txt-cli-ex
#
# COPYRIGHT: (C) 2010-2013 Ingo Karkat
#            (C) 2017 Nicolas Romero
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# v1.0 (11/01/2017): Test if priority is set before prioritization
#
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) PRIORITY \"THING I NEED TO DO +project @context\""
    echo "      Add a task and prioritize it in one step."
    echo ""
    exit
}

if [[ "$1" = [a-zA-Z] ]]; then
    pri=$1
    shift
fi

# Call back to the main script to add.
#"$TODO_FULL_SH" add "$@" || exit $?

if [ -n "$pri" ]; then
    # Figure out the line of what we just added, and prioritize it.
    item=$(sed -n '$ =' "$TODO_FILE") || exit $?
    "$TODO_FULL_SH" command pri "$item" $pri
fi
